#!/bin/bash
# Update apt package index
apt-get update -y
# Install nginx
apt-get -y install nginx
# Configure nginx to listen on port 80
sed -i 's/^\(.*listen .*:\).*$/\180;/' /etc/nginx/sites-available/default
# Restart nginx
service nginx restart
# Create HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html


