#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
sed -i 's/user www-data;/user nginx;/;s/listen 80;/listen 8080;/' /etc/nginx/nginx.conf /etc/nginx/sites-available/default
service nginx restart
